apiVersion: v1
kind: Secret
metadata:
  name: udacity-udagram-p3-aws-secret
type: Opaque
data:
  credentials: W2FseHQtYmVuXQphd3NfYWNjZXNzX2tleV9pZCA9IEFTSUFRUlNMRElKUEFaU0FaUzRXCmF3c19zZWNyZXRfYWNjZXNzX2tleSA9IHNZOWYyZytKbTdsYzJ6bG5RSmRLTEZHazIrcmxBa1RXZEtnc3Q2L2oKcmVnaW9uID0gdXMtZWFzdC0xCmF3c19zZXNzaW9uX3Rva2VuID0gRndvR1pYSXZZWGR6RUdrYURBSHE5V3lrL3RqUGJsSWw0Q0s4QWNtbjFjSHh1Q0lmTERGZDVYYzdSM3UzcWVjd1FrZUc5YTIrYUxSU0Vxb2lhM0NSbHdwQlFrMGxTeW1ESkhOSU5Pbkd3TmhiRlFyenV3SXByaWl1NlJ2Unc4c1JSTkI0NW9NUk9Xc1gvTFV2T2gveHY1MFBVd0dYYkh0ME5od0FXVWVoaVZMVllEZXhFSEZSblE2bDBJNDUybUkzOUZ6eUROYnhtakxLRlpZWFJMaHVCbUJadWxoSlo3Z0NNVTVLMy9obUNMd3p0cG5sbEN3aGVIdkZVK2xndm9VcEd1d0RyeC8xRTZhelJpMHpkeDdDWG9SbWRabDBCMkdpS0pXcGtwa0dNaTMzaDdHWmJlV3BZQW5zRlZpVm4yTVZ6TktOR3BaVk9xNHdEY1krdGpUYlg4TVBUbnI1cnNEQlF6bGsvZFk9Cg==
